#!/usr/bin/env python
"""Part A of build_final.py - builds pas_link.py from byte strings."""
import ast

parts = []

def P(s):
 parts.append(s)

P(b'"""ProjectAirSim bridge for DroneOS (GarudaOne)."""\n')
P(b'from __future__ import annotations\n')
P(b'import logging, math, os, time\n')
P(b'from dataclasses import dataclass, field\n')
P(b'from enum import StrEnum\n')
P(b'from typing import Any\n')
P(b'import projectairsim as pas\n')
P(b'\n')
P(b'LOG = logging.getLogger(__name__)\n')
P(b'\n')
P(b'class LinkState(StrEnum):\n')
P(b' DISCONNECTED = "disconnected"\n')
P(b' CONNECTING = "connecting"\n')
P(b' CONNECTED = "connected"\n')
P(b' STREAMING = "streaming"\n')
P(b' OFFBOARD_ENGAGED = "offboard_engaged"\n')
P(b' PX4_LAND = "px4_land"\n')
P(b' PX4_RTL = "px4_rtl"\n')
P(b' ERROR = "error"\n')
P(b'\n')
P(b'@dataclass\n')
P(b'class Setpoint:\n')
P(b' vx: float = 0.0\n')
P(b' vy: float = 0.0\n')
P(b' vz: float = 0.0\n')
P(b' yaw_rate: float = 0.0\n')
P(b' ts: float = field(default_factory=time.monotonic)\n')
P(b'\n')
P(b'@dataclass\n')
P(b'class TelemetryState:\n')
P(b' has_valid_bbox: bool = False\n')
P(b' bbox_confidence: float = 0.0\n')
P(b' target_id = None\n')
P(b' last_bbox_time: float = 0.0\n')
P(b' target_lost_time: float = 0.0\n')
P(b' search_start_time: float = 0.0\n')
P(b' last_grant_was_track: bool = False\n')
P(b' cpu_temp_c: float = 0.0\n')
P(b' cpu_temp_valid: bool = False\n')
P(b' battery_voltage: float = 0.0\n')
P(b' battery_valid: bool = False\n')
P(b' tof_min_range_m: float = 0.0\n')
P(b' tof_confidence: float = 0.0\n')
P(b' horiz_distance_m: float = 0.0\n')
P(b' alt_m: float = 0.0\n')
P(b' armed: bool = False\n')
P(b' landed: bool = True\n')
P(b' landed_valid: bool = False\n')
P(b' position_valid: bool = False\n')
P(b' last_setpoint_time: float = 0.0\n')
P(b' setpoint_streaming: bool = False\n')
P(b' gimbal_heartbeat_ok: bool = False\n')
P(b' last_gimbal_heartbeat: float = 0.0\n')
P(b' ekf_degraded: bool = True\n')
P(b'\n')

# Save parts to a pickle-like file for part B to continue
import pickle
with open(r'C:\Projects\GarudaOS\ProjectAirSim\_install\build_state.pkl', 'wb') as f:
 pickle.dump(parts, f)
print(f'Part A: {len(parts)} parts saved')
