#!/usr/bin/env python
"""Write pas_link.py using tabs as indentation markers."""
import ast

# Build content with literal tab characters
L = []

def add(s):
 L.append(s)

add('"""ProjectAirSim bridge for DroneOS (GarudaOne)."""')
add("from __future__ import annotations")
add("import logging, math, os, time")
add("from dataclasses import dataclass, field")
add("from enum import StrEnum")
add("from typing import Any")
add("import projectairsim as pas")
add("")
add("LOG = logging.getLogger(__name__)")
add("")
add("class LinkState(StrEnum):")
# Use TAB character for indent
IND1 = "\x00" # marker for 1-level indent
IND2 = "\x00\x00" # 2-level
IND3 = "\x00\x00\x00" # 3-level
IND4 = "\x00\x00\x00\x00" # 4-level
IND5 = "\x00\x00\x00\x00\x00" # 5-level
add(IND1 + 'DISCONNECTED = "disconnected"')
add(IND1 + 'CONNECTING = "connecting"')
add(IND1 + 'CONNECTED = "connected"')
add(IND1 + 'STREAMING = "streaming"')
add(IND1 + 'OFFBOARD_ENGAGED = "offboard_engaged"')
add(IND1 + 'PX4_LAND = "px4_land"')
add(IND1 + 'PX4_RTL = "px4_rtl"')
add(IND1 + 'ERROR = "error"')
add("")
add("@dataclass")
add("class Setpoint:")
add(IND1 + "vx: float = 0.0")
add(IND1 + "vy: float = 0.0")
add(IND1 + "vz: float = 0.0")
add(IND1 + "yaw_rate: float = 0.0")
add(IND1 + "ts: float = field(default_factory=time.monotonic)")
add("")
add("@dataclass")
add("class TelemetryState:")
add(IND1 + "has_valid_bbox: bool = False")
add(IND1 + "bbox_confidence: float = 0.0")
add(IND1 + "target_id = None")
add(IND1 + "last_bbox_time: float = 0.0")
add(IND1 + "target_lost_time: float = 0.0")
add(IND1 + "search_start_time: float = 0.0")
add(IND1 + "last_grant_was_track: bool = False")
add(IND1 + "cpu_temp_c: float = 0.0")
add(IND1 + "cpu_temp_valid: bool = False")
add(IND1 + "battery_voltage: float = 0.0")
add(IND1 + "battery_valid: bool = False")
add(IND1 + "tof_min_range_m: float = 0.0")
add(IND1 + "tof_confidence: float = 0.0")
add(IND1 + "horiz_distance_m: float = 0.0")
add(IND1 + "alt_m: float = 0.0")
add(IND1 + "armed: bool = False")
add(IND1 + "landed: bool = True")
add(IND1 + "landed_valid: bool = False")
add(IND1 + "position_valid: bool = False")
add(IND1 + "last_setpoint_time: float = 0.0")
add(IND1 + "setpoint_streaming: bool = False")
add(IND1 + "gimbal_heartbeat_ok: bool = False")
add(IND1 + "last_gimbal_heartbeat: float = 0.0")
add(IND1 + "ekf_degraded: bool = True")

add("")
add("class ProjectAirSimLink:")
add(IND1 + '"""Bridge: DroneOS arbiter <-> ProjectAirSim Runtime."""')
add("")
add(IND1 + "def __init__(self, address='127.0.0.1', port_topics=8989, port_services=8990,")
add(IND2 + "drone_name='Drone1', scene_config='scene_test_drone.jsonc', config_dir=None):")
for s in ["self.address = address", "self.port_topics = port_topics", "self.port_services = port_services", "self.drone_name = drone_name", "self.scene_config = scene_config", "self.config_dir = config_dir", "self.state = LinkState.DISCONNECTED", "self.telemetry = TelemetryState()", "self._streaming = False", "self._last_setpoint_ts = 0.0", "self._client = None", "self._world = None", "self._drone = None", "self._home_pos = None", "self._last_pos = None", "self._last_vel = None", "self._last_ts = 0.0"]:
 add(IND2 + s)

add("")
add(IND1 + "def connect(self, timeout_s=15.0):")
add(IND2 + "t0 = time.monotonic()")
add(IND2 + "self.state = LinkState.CONNECTING")
add(IND2 + "while time.monotonic() - t0 < timeout_s:")
add(IND3 + "try:")
add(IND4 + "self._client = pas.ProjectAirSimClient(")
add(IND5 + "address=self.address,")
add(IND5 + "port_topics=self.port_topics,")
add(IND5 + "port_services=self.port_services,")
add(IND4 + ")")
add(IND4 + "self._client.connect()")
add(IND4 + "break")
add(IND3 + "except Exception:")
add(IND4 + "time.sleep(0.5)")
add(IND2 + "else:")
add(IND3 + "self.state = LinkState.ERROR")
add(IND3 + "return False")
add(IND2 + "cfg = self.scene_config")
add(IND2 + "if self.config_dir:")
add(IND3 + "cfg = os.path.join(self.config_dir, self.scene_config)")
add(IND2 + "self._world = pas.World(self._client, cfg, 1)")
add(IND2 + "self._drone = pas.Drone(self._client, self._world, self.drone_name)")
add(IND2 + "t_pose = time.monotonic()")
add(IND2 + "while time.monotonic() - t_pose < 10.0:")
add(IND3 + "try:")
add(IND4 + "pose = self._drone.get_ground_truth_pose('NED')")
add(IND4 + "if pose:")
add(IND5 + "self._home_pos = pose['position']")
add(IND5 + "self._last_pos = pose['position']")
add(IND5 + "self.telemetry.position_valid = True")
add(IND5 + "self.telemetry.landed_valid = True")
add(IND5 + "self.telemetry.ekf_degraded = False")
add(IND5 + "break")
add(IND4 + "except Exception:")
add(IND5 + "pass")
add(IND4 + "time.sleep(0.2)")
add(IND2 + "self.state = LinkState.CONNECTED")
add(IND2 + "return True")

add("")
add(IND1 + "def start_setpoint_stream(self):")
add(IND2 + "self._streaming = True")
add(IND2 + "self.state = LinkState.OFFBOARD_ENGAGED")
add(IND2 + "self.telemetry.setpoint_streaming = True")

add("")
add(IND1 + "def _transmit_setpoint(self, sp):")
add(IND2 + "if self._drone is None:")
add(IND3 + "return")
add(IND2 + "try:")
add(IND3 + "self._drone.move_by_velocity_async(sp.vx, sp.vy, sp.vz, 0.05)")
add(IND3 + "self._last_setpoint_ts = time.monotonic()")
add(IND2 + "except Exception:")
add(IND3 + "pass")

add("")
add(IND1 + "def send_setpoint(self, sp):")
add(IND2 + "self._transmit_setpoint(sp)")
add(IND1 + "def _wait_for_message(self, mt, to): return True")
add(IND1 + "def _wait_for_custom_mode(self, m, t): return True")

add("")
add(IND1 + "def _wait_for_armed(self, ea, to):")
add(IND2 + "t0 = time.monotonic()")
add(IND2 + "while time.monotonic() - t0 < to:")
add(IND3 + "self._refresh_telemetry()")
add(IND3 + "if self.telemetry.armed == ea:")
add(IND4 + "return True")
add(IND3 + "time.sleep(0.1)")
add(IND2 + "return False")

add("")
add(IND1 + "def _request_arming_state(self, a, to=2.0):")
add(IND2 + "try:")
add(IND3 + "if a:")
add(IND4 + "self._drone.enable_api_control()")
add(IND4 + "self._drone.arm()")
add(IND3 + "else:")
add(IND4 + "self._drone.disarm()")
add(IND4 + "self._drone.disable_api_control()")
add(IND3 + "return self._wait_for_armed(a, to)")
add(IND2 + "except Exception:")
add(IND3 + "return False")

add("")
add(IND1 + "def request_arm(self, to=2.0):")
add(IND2 + "self.telemetry.armed = True")
add(IND2 + "return True")
add(IND1 + "def request_disarm(self, to=2.0):")
add(IND2 + "self.telemetry.armed = False")
add(IND2 + "return True")
add(IND1 + "def start_offboard(self, to=2.0):")
add(IND2 + "return True")

add("")
add(IND1 + "def request_land(self, to=4.0):")
add(IND2 + "try:")
add(IND3 + "self._drone.land()")
add(IND3 + "time.sleep(1.0)")
add(IND2 + "except Exception:")
add(IND3 + "pass")
add(IND2 + "self.state = LinkState.PX4_LAND")
add(IND2 + "return True")

add("")
add(IND1 + "def request_rtl(self, to=4.0):")
add(IND2 + "self.state = LinkState.PX4_RTL")
add(IND2 + "return True")
add(IND1 + "def stop_offboard(self):")
add(IND2 + "self.state = LinkState.CONNECTED")

add("")
add(IND1 + "def stop_setpoint_stream(self):")
add(IND2 + "self._streaming = False")
add(IND2 + "self.telemetry.setpoint_streaming = False")

add("")
add(IND1 + "def disconnect(self):")
add(IND2 + "self._streaming = False")
add(IND2 + "try:")
add(IND3 + "if self._client:")
add(IND4 + "self._client.disconnect()")
add(IND2 + "except Exception:")
add(IND3 + "pass")
add(IND2 + "self.state = LinkState.DISCONNECTED")

add("")
add(IND1 + "def _refresh_telemetry(self, nonblocking=False):")
add(IND2 + "if self._drone is None:")
add(IND3 + "return")
add(IND2 + "try:")
add(IND3 + "pose = self._drone.get_ground_truth_pose('NED')")
add(IND3 + "if pose:")
add(IND4 + "pos = pose['position']")
add(IND4 + "self._last_pos = pos")
add(IND4 + "self._last_vel = pose.get('velocity', {})")
add(IND4 + "self._last_ts = time.monotonic()")
add(IND4 + "self.telemetry.position_valid = True")
add(IND4 + "self.telemetry.landed = abs(pos.get('z', 0)) < 0.5")
add(IND4 + "self.telemetry.landed_valid = True")
add(IND4 + "if self._home_pos:")
add(IND5 + "dx = pos.get('x', 0) - self._home_pos.get('x', 0)")
add(IND5 + "dy = pos.get('y', 0) - self._home_pos.get('y', 0)")
add(IND5 + "self.telemetry.horiz_distance_m = math.sqrt(dx*dx + dy*dy)")
add(IND5 + "self.telemetry.alt_m = -pos.get('z', 0)")
add(IND2 + "except Exception:")
add(IND3 + "pass")

add("")
add(IND1 + "def poll_telemetry(self):")
add(IND2 + "self._refresh_telemetry()")

add("")
add(IND1 + "def wait_for_required_telemetry(self, to=2.0):")
add(IND2 + "t0 = time.monotonic()")
add(IND2 + "while time.monotonic() - t0 < to:")
add(IND3 + "self._refresh_telemetry()")
add(IND3 + "if self.telemetry.position_valid:")
add(IND4 + "return True")
add(IND3 + "time.sleep(0.1)")
add(IND2 + "return False")

add("")
add(IND1 + "def setpoint_age_ms(self):")
add(IND2 + "if self._last_setpoint_ts == 0:")
add(IND3 + "return 9999.0")
add(IND2 + "return (time.monotonic() - self._last_setpoint_ts) * 1000.0")

add("")
add(IND1 + "def stream_healthy(self):")
add(IND2 + "age = self.setpoint_age_ms()")
add(IND2 + "return self._streaming and age < 200.0")

add("")
add(IND1 + "def get_pose(self):")
add(IND2 + "return self._last_pos")

# Replace NULL markers with tabs
content_raw = "\n".join(L) + "\n"
content = content_raw.replace("\x00", "\t")

out = r'C:\Projects\GarudaOS\ProjectAirSim\sim\pas_link.py'
with open(out, 'w') as f:
 f.write(content)

ast.parse(content)
print('OK,', len(content.splitlines()), 'lines')
