#!/usr/bin/env python
"""Build drone_os.py - all code has NO leading spaces in this file.
Indentation is added programmatically via SP + line concatenation.
"""
import ast

SP = b' '
L = []

def add(n, s):
 L.append(SP * n + s)

add(0, b'"""')
add(0, b'DroneOS (GarudaOne) - unified drone control framework.')
add(0, b'')
add(0, b'Backends:')
add(0, b' PX4-Primary -> real hardware (PX4 + pymavlink)')
add(0, b' ProjectAirSim -> simulated flight (projectairsim)')
add(0, b'"""')
add(0, b'from __future__ import annotations')
add(0, b'from typing import Any, Protocol')
add(0, b'from dataclasses import dataclass')
add(0, b'import time')
add(0, b'')
add(0, b'# Optional real-hw backend')
add(0, b'try:')
add(1, b'from pymavlink import mavutil # type: ignore')
add(1, b'PYMAVLINK_AVAILABLE = True')
add(0, b'except ImportError:')
add(1, b'PYMAVLINK_AVAILABLE = False')
add(0, b'')
add(0, b'# Sim backend (installed alongside this package)')
add(0, b'from sim.pas_link import ProjectAirSimLink, LinkState, Setpoint, TelemetryState')
add(0, b'')
add(0, b'')
add(0, b'class DroneOS:')
add(1, b'"""Unified DroneOS flight controller with pluggable link backend."""')
add(0, b'')
add(1, b'def __init__(self, backend: str = "sim", link: Any | None = None):')
add(2, b'self.backend = backend')
add(2, b'self._link = link')
add(2, b'self._armed = False')
add(2, b'self._offboard = False')
add(2, b'self._setpoint_thread_running = False')
add(0, b'')
add(1, b'@staticmethod')
add(1, b'def _detect_backend() -> str:')
add(2, b'"""Return the default backend based on environment."""')
add(2, b'import os')
add(2, b'if os.environ.get("DRONEOS_BACKEND"):')
add(3, b'return os.environ["DRONEOS_BACKEND"].lower()')
add(2, b'# If pymavlink is installed and MAVLink router reachable, prefer real HW')
add(2, b'if PYMAVLINK_AVAILABLE:')
add(3, b'return "px4"')
add(2, b'return "sim"')
add(0, b'')
add(1, b'@classmethod')
add(1, b'def connect(cls, backend: str = "auto") -> "DroneOS":')
add(2, b'"""Factory: auto-detect or honour explicit backend, then connect."""')
add(2, b'if backend == "auto":')
add(3, b'backend = cls._detect_backend()')
add(2, b'print(f"[DroneOS] Using backend: {backend}")')
add(2, b'return cls(backend=backend)')
add(0, b'')
add(1, b'def arm(self, timeout: float = 2.0) -> bool:')
add(2, b'"""Arm the drone (idempotent in sim)."""')
add(2, b'self._link.request_arm(timeout)')
add(2, b'self._armed = True')
add(2, b'print("[DroneOS] Armed")')
add(2, b'return True')
add(0, b'')
add(1, b'def disarm(self, timeout: float = 2.0) -> bool:')
add(2, b'self._link.request_disarm(timeout)')
add(2, b'self._armed = False')
add(2, b'print("[DroneOS] Disarmed")')
add(2, b'return True')
add(0, b'')
add(1, b'def start_offboard(self) -> bool:')
add(2, b'self._link.start_offboard()')
add(2, b'self._offboard = True')
add(2, b'self._link.start_setpoint_stream()')
add(2, b'print("[DroneOS] Offboard mode ENGAGED")')
add(2, b'return True')
add(0, b'')
add(1, b'def stop_offboard(self) -> None:')
add(2, b'self._link.stop_offboard()')
add(2, b'self._link.stop_setpoint_stream()')
add(2, b'self._offboard = False')
add(2, b'print("[DroneOS] Offboard mode DISENGAGED")')
add(0, b'')
add(1, b'def send_velocity(self, vx: float, vy: float, vz: float, yaw_rate: float = 0.0):')
add(2, b'sp = Setpoint(vx=vx, vy=vy, vz=vz, yaw_rate=yaw_rate)')
add(2, b'self._link.send_setpoint(sp)')
add(0, b'')
add(1, b'def land(self, timeout: float = 4.0) -> bool:')
add(2, b'self.stop_offboard()')
add(2, b'return self._link.request_land(timeout)')
add(0, b'')
add(1, b'def rtl(self, timeout: float = 4.0) -> bool:')
add(2, b'self.stop_offboard()')
add(2, b'return self._link.request_rtl(timeout)')
add(0, b'')
add(1, b'def disconnect(self) -> None:')
add(2, b'self.stop_offboard()')
add(2, b'self._link.disconnect()')
add(2, b'print("[DroneOS] Disconnected")')
add(0, b'')
add(1, b'def poll(self) -> dict:')
add(2, b'self._link.poll_telemetry()')
add(2, b'return {')
add(3, b'"armed": self._link.telemetry.armed,')
add(3, b'"landed": self._link.telemetry.landed,')
add(3, b'"position_valid": self._link.telemetry.position_valid,')
add(3, b'"horiz_distance_m": self._link.telemetry.horiz_distance_m,')
add(3, b'"alt_m": self._link.telemetry.alt_m,')
add(3, b'"ekf_degraded": self._link.telemetry.ekf_degraded,')
add(3, b'"stream_healthy": self._link.stream_healthy(),')
add(3, b'"state": self._link.state,')
add(2, b'}')

# Write
data = b'\n'.join(L) + b'\n'
out = r'C:\Projects\GarudaOS\GarudaOne\drone\drone_os.py'
import os
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, 'wb') as f:
 f.write(data)

ast.parse(data.decode('utf-8'))
print('OK:', len(data.decode().splitlines()), 'lines')
