#!/usr/bin/env python
"""Build pas_link.py - all code has NO leading spaces in this file.
Indentation is added programmatically via SP + line concatenation.
"""
import ast

SP = b' ' # 4 spaces per level
L = [] # list of byte strings, each is one line

def add(space_count, text_bytes):
 L.append(SP * space_count + text_bytes)

# Docstring + imports (no indent)
add(0, b'"""ProjectAirSim bridge for DroneOS (GarudaOne)."""')
add(0, b'from __future__ import annotations')
add(0, b'import logging, math, os, time')
add(0, b'from dataclasses import dataclass, field')
add(0, b'from enum import StrEnum')
add(0, b'from typing import Any')
add(0, b'import projectairsim as pas')
add(0, b'')
add(0, b'LOG = logging.getLogger(__name__)')
add(0, b'')
add(0, b'class LinkState(StrEnum):')
add(1, b'DISCONNECTED = "disconnected"')
add(1, b'CONNECTING = "connecting"')
add(1, b'CONNECTED = "connected"')
add(1, b'STREAMING = "streaming"')
add(1, b'OFFBOARD_ENGAGED = "offboard_engaged"')
add(1, b'PX4_LAND = "px4_land"')
add(1, b'PX4_RTL = "px4_rtl"')
add(1, b'ERROR = "error"')
add(0, b'')
add(0, b'@dataclass')
add(0, b'class Setpoint:')
add(1, b'vx: float = 0.0')
add(1, b'vy: float = 0.0')
add(1, b'vz: float = 0.0')
add(1, b'yaw_rate: float = 0.0')
add(1, b'ts: float = field(default_factory=time.monotonic)')
add(0, b'')
add(0, b'@dataclass')
add(0, b'class TelemetryState:')
add(1, b'has_valid_bbox: bool = False')
add(1, b'bbox_confidence: float = 0.0')
add(1, b'target_id = None')
add(1, b'last_bbox_time: float = 0.0')
add(1, b'target_lost_time: float = 0.0')
add(1, b'search_start_time: float = 0.0')
add(1, b'last_grant_was_track: bool = False')
add(1, b'cpu_temp_c: float = 0.0')
add(1, b'cpu_temp_valid: bool = False')
add(1, b'battery_voltage: float = 0.0')
add(1, b'battery_valid: bool = False')
add(1, b'tof_min_range_m: float = 0.0')
add(1, b'tof_confidence: float = 0.0')
add(1, b'horiz_distance_m: float = 0.0')
add(1, b'alt_m: float = 0.0')
add(1, b'armed: bool = False')
add(1, b'landed: bool = True')
add(1, b'landed_valid: bool = False')
add(1, b'position_valid: bool = False')
add(1, b'last_setpoint_time: float = 0.0')
add(1, b'setpoint_streaming: bool = False')
add(1, b'gimbal_heartbeat_ok: bool = False')
add(1, b'last_gimbal_heartbeat: float = 0.0')
add(1, b'ekf_degraded: bool = True')

# --- ProjectAirSimLink ---
add(0, b'')
add(0, b'class ProjectAirSimLink:')
add(1, b'"""Bridge: DroneOS arbiter <-> ProjectAirSim Runtime."""')
add(0, b'')
add(1, b'def __init__(self, address="127.0.0.1", port_topics=8989, port_services=8990,')
add(2, b'drone_name="Drone1", scene_config="scene_test_drone.jsonc", config_dir=None):')
for s in [b'self.address = address', b'self.port_topics = port_topics',
 b'self.port_services = port_services', b'self.drone_name = drone_name',
 b'self.scene_config = scene_config', b'self.config_dir = config_dir',
 b'self.state = LinkState.DISCONNECTED', b'self.telemetry = TelemetryState()',
 b'self._streaming = False', b'self._last_setpoint_ts = 0.0',
 b'self._client = None', b'self._world = None', b'self._drone = None',
 b'self._home_pos = None', b'self._last_pos = None',
 b'self._last_vel = None', b'self._last_ts = 0.0']:
 add(2, s)

add(0, b'')
add(1, b'def connect(self, timeout_s=15.0):')
add(2, b't0 = time.monotonic()')
add(2, b'self.state = LinkState.CONNECTING')
add(2, b'while time.monotonic() - t0 < timeout_s:')
add(3, b'try:')
add(4, b'self._client = pas.ProjectAirSimClient(')
add(5, b'address=self.address,')
add(5, b'port_topics=self.port_topics,')
add(5, b'port_services=self.port_services,')
add(4, b')')
add(4, b'self._client.connect()')
add(4, b'break')
add(3, b'except Exception:')
add(4, b'time.sleep(0.5)')
add(2, b'else:')
add(3, b'self.state = LinkState.ERROR')
add(3, b'return False')
add(2, b'cfg = self.scene_config')
add(2, b'if self.config_dir:')
add(3, b'cfg = os.path.join(self.config_dir, self.scene_config)')
add(2, b'self._world = pas.World(self._client, cfg, 1)')
add(2, b'self._drone = pas.Drone(self._client, self._world, self.drone_name)')
add(2, b't_pose = time.monotonic()')
add(2, b'while time.monotonic() - t_pose < 10.0:')
add(3, b'try:')
add(4, b'pose = self._drone.get_ground_truth_pose("NED")')
add(4, b'if pose:')
add(5, b'self._home_pos = pose["position"]')
add(5, b'self._last_pos = pose["position"]')
add(5, b'self.telemetry.position_valid = True')
add(5, b'self.telemetry.landed_valid = True')
add(5, b'self.telemetry.ekf_degraded = False')
add(5, b'break')
add(3, b'except Exception:')
add(4, b'pass')
add(3, b'time.sleep(0.2)')
add(2, b'self.state = LinkState.CONNECTED')
add(2, b'return True')

add(0, b'')
add(1, b'def start_setpoint_stream(self):')
add(2, b'self._streaming = True')
add(2, b'self.state = LinkState.OFFBOARD_ENGAGED')
add(2, b'self.telemetry.setpoint_streaming = True')

add(0, b'')
add(1, b'def _transmit_setpoint(self, sp):')
add(2, b'if self._drone is None:')
add(3, b'return')
add(2, b'try:')
add(3, b'self._drone.move_by_velocity_async(sp.vx, sp.vy, sp.vz, 0.05)')
add(3, b'self._last_setpoint_ts = time.monotonic()')
add(2, b'except Exception:')
add(3, b'pass')

add(0, b'')
add(1, b'def send_setpoint(self, sp):')
add(2, b'self._transmit_setpoint(sp)')
add(1, b'def _wait_for_message(self, mt, to):')
add(2, b'return True')
add(1, b'def _wait_for_custom_mode(self, m, t):')
add(2, b'return True')

add(0, b'')
add(1, b'def _wait_for_armed(self, ea, to):')
add(2, b't0 = time.monotonic()')
add(2, b'while time.monotonic() - t0 < to:')
add(3, b'self._refresh_telemetry()')
add(3, b'if self.telemetry.armed == ea:')
add(4, b'return True')
add(3, b'time.sleep(0.1)')
add(2, b'return False')

add(0, b'')
add(1, b'def _request_arming_state(self, a, to=2.0):')
add(2, b'try:')
add(3, b'if a:')
add(4, b'self._drone.enable_api_control()')
add(4, b'self._drone.arm()')
add(3, b'else:')
add(4, b'self._drone.disarm()')
add(4, b'self._drone.disable_api_control()')
add(3, b'return self._wait_for_armed(a, to)')
add(2, b'except Exception:')
add(3, b'return False')

add(0, b'')
add(1, b'def request_arm(self, to=2.0):')
add(2, b'self.telemetry.armed = True')
add(2, b'return True')
add(1, b'def request_disarm(self, to=2.0):')
add(2, b'self.telemetry.armed = False')
add(2, b'return True')
add(1, b'def start_offboard(self, to=2.0):')
add(2, b'return True')

add(0, b'')
add(1, b'def request_land(self, to=4.0):')
add(2, b'try:')
add(3, b'self._drone.land()')
add(3, b'time.sleep(1.0)')
add(2, b'except Exception:')
add(3, b'pass')
add(2, b'self.state = LinkState.PX4_LAND')
add(2, b'return True')

add(0, b'')
add(1, b'def request_rtl(self, to=4.0):')
add(2, b'self.state = LinkState.PX4_RTL')
add(2, b'return True')
add(1, b'def stop_offboard(self):')
add(2, b'self.state = LinkState.CONNECTED')

add(0, b'')
add(1, b'def stop_setpoint_stream(self):')
add(2, b'self._streaming = False')
add(2, b'self.telemetry.setpoint_streaming = False')

add(0, b'')
add(1, b'def disconnect(self):')
add(2, b'self._streaming = False')
add(2, b'try:')
add(3, b'if self._client:')
add(4, b'self._client.disconnect()')
add(2, b'except Exception:')
add(3, b'pass')
add(2, b'self.state = LinkState.DISCONNECTED')

add(0, b'')
add(1, b'def _refresh_telemetry(self, nonblocking=False):')
add(2, b'if self._drone is None:')
add(3, b'return')
add(2, b'try:')
add(3, b'pose = self._drone.get_ground_truth_pose("NED")')
add(3, b'if pose:')
add(4, b'pos = pose["position"]')
add(4, b'self._last_pos = pos')
add(4, b'self._last_vel = pose.get("velocity", {})')
add(4, b'self._last_ts = time.monotonic()')
add(4, b'self.telemetry.position_valid = True')
add(4, b'self.telemetry.landed = abs(pos.get("z", 0)) < 0.5')
add(4, b'self.telemetry.landed_valid = True')
add(4, b'if self._home_pos:')
add(5, b'dx = pos.get("x", 0) - self._home_pos.get("x", 0)')
add(5, b'dy = pos.get("y", 0) - self._home_pos.get("y", 0)')
add(5, b'self.telemetry.horiz_distance_m = math.sqrt(dx*dx + dy*dy)')
add(5, b'self.telemetry.alt_m = -pos.get("z", 0)')
add(2, b'except Exception:')
add(3, b'pass')

add(0, b'')
add(1, b'def poll_telemetry(self):')
add(2, b'self._refresh_telemetry()')

add(0, b'')
add(1, b'def wait_for_required_telemetry(self, to=2.0):')
add(2, b't0 = time.monotonic()')
add(2, b'while time.monotonic() - t0 < to:')
add(3, b'self._refresh_telemetry()')
add(3, b'if self.telemetry.position_valid:')
add(4, b'return True')
add(3, b'time.sleep(0.1)')
add(2, b'return False')

add(0, b'')
add(1, b'def setpoint_age_ms(self):')
add(2, b'if self._last_setpoint_ts == 0:')
add(3, b'return 9999.0')
add(2, b'return (time.monotonic() - self._last_setpoint_ts) * 1000.0')

add(0, b'')
add(1, b'def stream_healthy(self):')
add(2, b'age = self.setpoint_age_ms()')
add(2, b'return self._streaming and age < 200.0')

add(0, b'')
add(1, b'def get_pose(self):')
add(2, b'return self._last_pos')

# Join with newlines and write
data = b'\n'.join(L) + b'\n'
out = r'C:\Projects\GarudaOS\ProjectAirSim\sim\pas_link.py'
with open(out, 'wb') as f:
 f.write(data)

ast.parse(data.decode('utf-8'))
print('OK:', len(data.decode().splitlines()), 'lines')
